# [workspace]
[package]
name = "nanogl"
authors = ["Jacky Song"]
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
# Will remove libc once
# custom reimplementation is
# complete
libc = "0.2"
